# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

import echoservice_pb2 as echoservice__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in echoservice_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EchoServiceStub(object):
    """Echo service.
    A simple service that echoes messages back in uppercase.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
            "/echo.v1.EchoService/Echo",
            request_serializer=echoservice__pb2.EchoRequest.SerializeToString,
            response_deserializer=echoservice__pb2.EchoResponse.FromString,
            _registered_method=True,
        )


class EchoServiceServicer(object):
    """Echo service.
    A simple service that echoes messages back in uppercase.
    """

    def Echo(self, request, context):
        """Echo the message back in uppercase.

        Args:
        request (EchoRequest): The request message.

        Returns:
        EchoResponse: The response message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Echo": grpc.unary_unary_rpc_method_handler(
            servicer.Echo,
            request_deserializer=echoservice__pb2.EchoRequest.FromString,
            response_serializer=echoservice__pb2.EchoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "echo.v1.EchoService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("echo.v1.EchoService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """Echo service.
    A simple service that echoes messages back in uppercase.
    """

    @staticmethod
    def Echo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/echo.v1.EchoService/Echo",
            echoservice__pb2.EchoRequest.SerializeToString,
            echoservice__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
