# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

import barservice_pb2 as barservice__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in barservice_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bar = channel.unary_unary(
            "/bar.v1.BarService/Bar",
            request_serializer=barservice__pb2.BarRequest.SerializeToString,
            response_deserializer=barservice__pb2.BarResponse.FromString,
            _registered_method=True,
        )


class BarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Bar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Bar": grpc.unary_unary_rpc_method_handler(
            servicer.Bar,
            request_deserializer=barservice__pb2.BarRequest.FromString,
            response_serializer=barservice__pb2.BarResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "bar.v1.BarService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("bar.v1.BarService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class BarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Bar(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/bar.v1.BarService/Bar",
            barservice__pb2.BarRequest.SerializeToString,
            barservice__pb2.BarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
