# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import fooservice_pb2 as fooservice__pb2


class FooServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Foo = channel.unary_unary(
            "/foo.v1.FooService/Foo",
            request_serializer=fooservice__pb2.FooRequest.SerializeToString,
            response_deserializer=fooservice__pb2.FooResponse.FromString,
        )


class FooServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Foo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FooServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Foo": grpc.unary_unary_rpc_method_handler(
            servicer.Foo,
            request_deserializer=fooservice__pb2.FooRequest.FromString,
            response_serializer=fooservice__pb2.FooResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "foo.v1.FooService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class FooService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Foo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/foo.v1.FooService/Foo",
            fooservice__pb2.FooRequest.SerializeToString,
            fooservice__pb2.FooResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
