# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fugaservice_pb2 as fugaservice__pb2


class FugaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Foo = channel.unary_unary(
                '/fuga.v1.FugaService/Foo',
                request_serializer=fugaservice__pb2.Request.SerializeToString,
                response_deserializer=fugaservice__pb2.Response.FromString,
                )


class FugaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Foo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FugaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Foo': grpc.unary_unary_rpc_method_handler(
                    servicer.Foo,
                    request_deserializer=fugaservice__pb2.Request.FromString,
                    response_serializer=fugaservice__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fuga.v1.FugaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FugaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Foo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fuga.v1.FugaService/Foo',
            fugaservice__pb2.Request.SerializeToString,
            fugaservice__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
