# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fugaservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ugaservice.proto\x12\x07\x66uga.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n\x08Response\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12#\n\x01\x64\x18\x03 \x03(\x0b\x32\x18.fuga.v1.Response.DEntry\x12)\n\x0bm_MyMessage\x18\x04 \x01(\x0b\x32\x12.fuga.v1.MyMessageH\x00\x12\x12\n\x08m_string\x18\x05 \x01(\tH\x00\x1a(\n\x06\x44\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x03\n\x01m\"\x81\x01\n\tMyMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x11\n\x07o_int32\x18\x03 \x01(\x05H\x00\x12\x41\n\x1bo_google_protobuf_Timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x42\x03\n\x01o\"\x91\x01\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\"\n\x01\x64\x18\x03 \x03(\x0b\x32\x17.fuga.v1.Request.DEntry\x12\x1d\n\x01m\x18\x04 \x01(\x0b\x32\x12.fuga.v1.MyMessage\x1a(\n\x06\x44\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x39\n\x0b\x46ugaService\x12*\n\x03\x46oo\x12\x10.fuga.v1.Request\x1a\x11.fuga.v1.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fugaservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE_DENTRY._options = None
  _RESPONSE_DENTRY._serialized_options = b'8\001'
  _REQUEST_DENTRY._options = None
  _REQUEST_DENTRY._serialized_options = b'8\001'
  _globals['_RESPONSE']._serialized_start=64
  _globals['_RESPONSE']._serialized_end=248
  _globals['_RESPONSE_DENTRY']._serialized_start=203
  _globals['_RESPONSE_DENTRY']._serialized_end=243
  _globals['_MYMESSAGE']._serialized_start=251
  _globals['_MYMESSAGE']._serialized_end=380
  _globals['_REQUEST']._serialized_start=383
  _globals['_REQUEST']._serialized_end=528
  _globals['_REQUEST_DENTRY']._serialized_start=203
  _globals['_REQUEST_DENTRY']._serialized_end=243
  _globals['_FUGASERVICE']._serialized_start=530
  _globals['_FUGASERVICE']._serialized_end=587
# @@protoc_insertion_point(module_scope)
