# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hogeservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hogeservice.proto\x12\x07hoge.v1\"\x1c\n\x0b\x42\x61rResponse\x12\r\n\x05names\x18\x01 \x03(\t\"\x1b\n\nBarRequest\x12\r\n\x05names\x18\x01 \x03(\t\"z\n\x0b\x46ooResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12&\n\x01\x64\x18\x03 \x03(\x0b\x32\x1b.hoge.v1.FooResponse.DEntry\x1a(\n\x06\x44\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"x\n\nFooRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12%\n\x01\x64\x18\x03 \x03(\x0b\x32\x1a.hoge.v1.FooRequest.DEntry\x1a(\n\x06\x44\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32q\n\x0bHogeService\x12\x30\n\x03\x42\x61r\x12\x13.hoge.v1.BarRequest\x1a\x14.hoge.v1.BarResponse\x12\x30\n\x03\x46oo\x12\x13.hoge.v1.FooRequest\x1a\x14.hoge.v1.FooResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hogeservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FOORESPONSE_DENTRY._options = None
  _FOORESPONSE_DENTRY._serialized_options = b'8\001'
  _FOOREQUEST_DENTRY._options = None
  _FOOREQUEST_DENTRY._serialized_options = b'8\001'
  _globals['_BARRESPONSE']._serialized_start=30
  _globals['_BARRESPONSE']._serialized_end=58
  _globals['_BARREQUEST']._serialized_start=60
  _globals['_BARREQUEST']._serialized_end=87
  _globals['_FOORESPONSE']._serialized_start=89
  _globals['_FOORESPONSE']._serialized_end=211
  _globals['_FOORESPONSE_DENTRY']._serialized_start=171
  _globals['_FOORESPONSE_DENTRY']._serialized_end=211
  _globals['_FOOREQUEST']._serialized_start=213
  _globals['_FOOREQUEST']._serialized_end=333
  _globals['_FOOREQUEST_DENTRY']._serialized_start=171
  _globals['_FOOREQUEST_DENTRY']._serialized_end=211
  _globals['_HOGESERVICE']._serialized_start=335
  _globals['_HOGESERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
