# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hogeservice_pb2 as hogeservice__pb2


class HogeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bar = channel.unary_unary(
                '/hoge.v1.HogeService/Bar',
                request_serializer=hogeservice__pb2.BarRequest.SerializeToString,
                response_deserializer=hogeservice__pb2.BarResponse.FromString,
                )
        self.Foo = channel.unary_unary(
                '/hoge.v1.HogeService/Foo',
                request_serializer=hogeservice__pb2.FooRequest.SerializeToString,
                response_deserializer=hogeservice__pb2.FooResponse.FromString,
                )


class HogeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Bar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Foo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HogeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bar': grpc.unary_unary_rpc_method_handler(
                    servicer.Bar,
                    request_deserializer=hogeservice__pb2.BarRequest.FromString,
                    response_serializer=hogeservice__pb2.BarResponse.SerializeToString,
            ),
            'Foo': grpc.unary_unary_rpc_method_handler(
                    servicer.Foo,
                    request_deserializer=hogeservice__pb2.FooRequest.FromString,
                    response_serializer=hogeservice__pb2.FooResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hoge.v1.HogeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HogeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Bar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hoge.v1.HogeService/Bar',
            hogeservice__pb2.BarRequest.SerializeToString,
            hogeservice__pb2.BarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Foo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hoge.v1.HogeService/Foo',
            hogeservice__pb2.FooRequest.SerializeToString,
            hogeservice__pb2.FooResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
