# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: olympicsagent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "olympicsagent.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13olympicsagent.proto\x12\x10olympicsagent.v1"-\n\x0c\x43ityLocation\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t"\x1d\n\rOlympicsQuery\x12\x0c\n\x04year\x18\x01 \x01(\x05"!\n\x0fStreamingResult\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t"3\n\x15OlympicsDurationQuery\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x32\xb2\x01\n\rOlympicsAgent\x12\x46\n\x03\x41sk\x12\x1f.olympicsagent.v1.OlympicsQuery\x1a\x1e.olympicsagent.v1.CityLocation\x12Y\n\tAskStream\x12\'.olympicsagent.v1.OlympicsDurationQuery\x1a!.olympicsagent.v1.StreamingResult0\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "olympicsagent_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CITYLOCATION"]._serialized_start = 41
    _globals["_CITYLOCATION"]._serialized_end = 86
    _globals["_OLYMPICSQUERY"]._serialized_start = 88
    _globals["_OLYMPICSQUERY"]._serialized_end = 117
    _globals["_STREAMINGRESULT"]._serialized_start = 119
    _globals["_STREAMINGRESULT"]._serialized_end = 152
    _globals["_OLYMPICSDURATIONQUERY"]._serialized_start = 154
    _globals["_OLYMPICSDURATIONQUERY"]._serialized_end = 205
    _globals["_OLYMPICSAGENT"]._serialized_start = 208
    _globals["_OLYMPICSAGENT"]._serialized_end = 386
# @@protoc_insertion_point(module_scope)
