# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import olympicsagent_pb2 as olympicsagent__pb2


class OlympicsAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
            "/olympicsagent.v1.OlympicsAgent/Ask",
            request_serializer=olympicsagent__pb2.OlympicsQuery.SerializeToString,
            response_deserializer=olympicsagent__pb2.CityLocation.FromString,
        )
        self.AskStream = channel.unary_stream(
            "/olympicsagent.v1.OlympicsAgent/AskStream",
            request_serializer=olympicsagent__pb2.OlympicsDurationQuery.SerializeToString,
            response_deserializer=olympicsagent__pb2.StreamingResult.FromString,
        )


class OlympicsAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AskStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OlympicsAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Ask": grpc.unary_unary_rpc_method_handler(
            servicer.Ask,
            request_deserializer=olympicsagent__pb2.OlympicsQuery.FromString,
            response_serializer=olympicsagent__pb2.CityLocation.SerializeToString,
        ),
        "AskStream": grpc.unary_stream_rpc_method_handler(
            servicer.AskStream,
            request_deserializer=olympicsagent__pb2.OlympicsDurationQuery.FromString,
            response_serializer=olympicsagent__pb2.StreamingResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "olympicsagent.v1.OlympicsAgent", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class OlympicsAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ask(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/olympicsagent.v1.OlympicsAgent/Ask",
            olympicsagent__pb2.OlympicsQuery.SerializeToString,
            olympicsagent__pb2.CityLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AskStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/olympicsagent.v1.OlympicsAgent/AskStream",
            olympicsagent__pb2.OlympicsDurationQuery.SerializeToString,
            olympicsagent__pb2.StreamingResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
